### ISSUE TITLE
How do you use this with livesplit one

### ISSUE THREAD

**Issue by Cloneian28** [cccarl/pizza-tower-autosplitter#1]
You cant load autosplitters into livesplit one, and the only way to use an autosplliter in livesplit one is via the livesplit server feature, so how do you use this on livesplit one?

**Comment by cccarl** [comment]
Oh hi, if you mean the website, it's not possible to use there. LiveSplit One one is technically a portable version that can be ported to many platforms and the web version is one of them.

Alternatives that support WASM autosplitters are the [LiveSplit One OBS plugin](https://github.com/LiveSplit/obs-livesplit-one) and the original LiveSplit for windows. There may be some experimental desktop apps somewhere but you would have to ask in the [speedrun tool dev discord server](https://discord.gg/N6wv8pW).

**Comment by Cloneian28** [comment]
That makes more sense, didn't know about the obs plugin, i've been looking for a way to get an autosplitter working on linux so ill give the plugin a try, thanks!
